#!/usr/bin/env bash

docker run -it --rm \
    -v "$PWD":/app \
    -p 8888:8888 \
    -v /home/v-work/Documents/P-A_ML_Fall2025/MyNotebooks/:/MyNotebooks \
    -v /home/v-work/Documents/P-A_ML_Fall2025/Notebooks/:/Notebooks \
    -v /home/v-work/Documents/P-A_ML_Fall2025/Kaggle/:/Kaggle \
    amd-pytorch-env \
    jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser "$@"

