#!/usr/bin/env  bash

docker run -it \
    --device=/dev/kfd \
    --device=/dev/dri \
    --group-add video \
    -v "$PWD":/app \
    -p 8888:8888 \
    -v /home/v-work/Documents/P-A_ML_Fall2025/MyNotebooks/:/MyNotebooks \
    -v /home/v-work/Documents/P-A_ML_Fall2025/Notebooks/:/Notebooks \
    amd-pytorch-env "$@" \
    jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser
    
